name: COVID-19
channels:
  - conda-forge
dependencies:
  - pandas
  - python=3.7
  - ipython
  - numpy
  - pip
  - nodejs
  - geopandas
  - ipywidgets
  - matplotlib
  - jupyterlab
  - descartes
  - voila
